const applications = [
  {
    id: 'APP-001',
    applicantName: 'Ahmed Al-Mansoori',
    email: 'ahmed@example.com',
    amount: 150000,
    tenor: 18,
    sector: 'Retail',
    dsr: 0.28,
    cashflow: 0.72,
    sectorRisk: 'medium',
    fraudRisk: 0.08,
    employmentStability: 0.85,
    bureauScore: 680,
    existingDebtBurden: 0.35,
    score: 724,
  },
  {
    id: 'APP-002',
    applicantName: 'Sara Nasser',
    email: 'sara@example.com',
    amount: 80000,
    tenor: 12,
    sector: 'Healthcare',
    dsr: 0.22,
    cashflow: 0.85,
    sectorRisk: 'low',
    fraudRisk: 0.03,
    employmentStability: 0.92,
    bureauScore: 750,
    existingDebtBurden: 0.20,
    score: 821,
  },
  {
    id: 'APP-003',
    applicantName: 'Mohammed Al-Rashidi',
    email: 'mohammed@example.com',
    amount: 320000,
    tenor: 36,
    sector: 'Construction',
    dsr: 0.45,
    cashflow: 0.35,
    sectorRisk: 'high',
    fraudRisk: 0.18,
    employmentStability: 0.45,
    bureauScore: 540,
    existingDebtBurden: 0.60,
    score: 432,
  },
  {
    id: 'APP-004',
    applicantName: 'Layla Al-Qassimi',
    email: 'layla@example.com',
    amount: 45000,
    tenor: 6,
    sector: 'Technology',
    dsr: 0.15,
    cashflow: 0.95,
    sectorRisk: 'low',
    fraudRisk: 0.01,
    employmentStability: 0.98,
    bureauScore: 820,
    existingDebtBurden: 0.10,
    score: 912,
  },
  {
    id: 'APP-005',
    applicantName: 'Khalid Al-Hammadi',
    email: 'khalid@example.com',
    amount: 180000,
    tenor: 24,
    sector: 'Agriculture',
    dsr: 0.38,
    cashflow: 0.55,
    sectorRisk: 'medium',
    fraudRisk: 0.12,
    employmentStability: 0.60,
    bureauScore: 610,
    existingDebtBurden: 0.45,
    score: 578,
  },
  {
    id: 'APP-006',
    applicantName: 'Noor Al-Siyabi',
    email: 'noor@example.com',
    amount: 95000,
    tenor: 18,
    sector: 'Retail',
    dsr: 0.32,
    cashflow: 0.70,
    sectorRisk: 'medium',
    fraudRisk: 0.06,
    employmentStability: 0.78,
    bureauScore: 690,
    existingDebtBurden: 0.38,
    score: 685,
  },
  {
    id: 'APP-007',
    applicantName: 'Faisal Al-Busaidi',
    email: 'faisal@example.com',
    amount: 210000,
    tenor: 30,
    sector: 'Construction',
    dsr: 0.52,
    cashflow: 0.28,
    sectorRisk: 'high',
    fraudRisk: 0.22,
    employmentStability: 0.38,
    bureauScore: 480,
    existingDebtBurden: 0.68,
    score: 356,
  },
  {
    id: 'APP-008',
    applicantName: 'Mariam Al-Khalili',
    email: 'mariam@example.com',
    amount: 65000,
    tenor: 12,
    sector: 'Healthcare',
    dsr: 0.18,
    cashflow: 0.90,
    sectorRisk: 'low',
    fraudRisk: 0.02,
    employmentStability: 0.95,
    bureauScore: 790,
    existingDebtBurden: 0.15,
    score: 875,
  },
  {
    id: 'APP-009',
    applicantName: 'Tariq Al-Maawali',
    email: 'tariq@example.com',
    amount: 130000,
    tenor: 20,
    sector: 'Technology',
    dsr: 0.25,
    cashflow: 0.78,
    sectorRisk: 'low',
    fraudRisk: 0.04,
    employmentStability: 0.88,
    bureauScore: 720,
    existingDebtBurden: 0.28,
    score: 764,
  },
  {
    id: 'APP-010',
    applicantName: 'Aisha Al-Blooshi',
    email: 'aisha@example.com',
    amount: 75000,
    tenor: 15,
    sector: 'Retail',
    dsr: 0.30,
    cashflow: 0.65,
    sectorRisk: 'medium',
    fraudRisk: 0.07,
    employmentStability: 0.72,
    bureauScore: 660,
    existingDebtBurden: 0.40,
    score: 628,
  },
]

const fraudAlerts = [
  {
    id: 'FRA-001',
    applicantName: 'Ahmed Al-Mansoori',
    email: 'ahmed@example.com',
    amount: 150000,
    riskLevel: 'HIGH',
    status: 'NEW',
    severity: 'high',
    assignee: 'Unassigned',
    similarityFlags: ['Similar to FRA-000'],
  },
  {
    id: 'FRA-002',
    applicantName: 'Sara Nasser',
    email: 'sara@example.com',
    amount: 80000,
    riskLevel: 'MEDIUM',
    status: 'ASSIGNED',
    severity: 'medium',
    assignee: 'Ahmed Khalid',
    similarityFlags: ['Similar to FRA-010'],
  },
  {
    id: 'FRA-003',
    applicantName: 'Mohammed Al-Rashidi',
    email: 'mohammed@example.com',
    amount: 320000,
    riskLevel: 'CRITICAL',
    status: 'INVESTIGATING',
    severity: 'high',
    assignee: 'Omar Fahad',
    similarityFlags: ['Similar to FRA-022', 'Linked to APP-003'],
  },
]

const kpiData = [
  { label: 'Total Applications', value: '142', trend: '+3.5%', suffix: '' },
  { label: 'Average Score', value: '672', trend: '+4.2%', suffix: '/1000' },
  { label: 'Approved Today', value: '8', trend: '+12%', suffix: '' },
  { label: 'Rejected (7 days)', value: '19', trend: '-8%', suffix: '' },
]

const sectorExposure = [
  { sector: 'Retail', exposure: 35, rating: 'medium' },
  { sector: 'Construction', exposure: 28, rating: 'high' },
  { sector: 'Healthcare', exposure: 18, rating: 'low' },
  { sector: 'Technology', exposure: 12, rating: 'medium' },
  { sector: 'Agriculture', exposure: 7, rating: 'low' },
]

const activityFeed = [
  { icon: '📄', text: '<a href="#">APP-003</a> scored <strong>432</strong>', time: '2 min ago' },
  { icon: '✅', text: 'APP-002 approved — <strong>821</strong>', time: '15 min ago' },
  { icon: '🔔', text: 'FRA-003 escalated by Omar Fahad', time: '42 min ago' },
  { icon: '📊', text: 'Monthly report generated', time: '1 hr ago' },
  { icon: '👤', text: 'Admin logged in from new device', time: '2 hr ago' },
]

const insights = [
  { id: 'INS-001', title: 'DSR Spike', severity: 'high', icon: '📈', color: 'var(--rose)' },
  { id: 'INS-002', title: 'Sector Risk', severity: 'medium', icon: '⚠️', color: 'var(--amber)' },
]

const smeApplications = [
  { id: 'SME-001', name: 'Al-Futtaim Enterprises', sector: 'Retail', amount: 250000 },
  { id: 'SME-002', name: 'Gulf Tech Solutions', sector: 'Technology', amount: 180000 },
]

const regulatoryDocs = [
  { id: 'REG-001', title: 'CBUAE Credit Scoring Guidelines', category: 'Regulatory', date: '2024-03-15' },
  { id: 'REG-002', title: 'AML Compliance Framework', category: 'AML', date: '2024-02-20' },
]

const profileData = {
  name: 'Ossama Admin',
  email: 'admin@rLens.ai',
  role: 'Admin',
  marketing: true,
  notifications: true,
}

export default {
  applications,
  fraudAlerts,
  kpiData,
  sectorExposure,
  activityFeed,
  insights,
  smeApplications,
  regulatoryDocs,
  profileData,
}
